services:
  - type: web
    name: n8n
    runtime: docker
    env: docker
    plan: free
    region: oregon
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_CONNECTION_URL
        value: postgresql://neondb_owner:npg_qjkALd13tRhW@ep-misty-star-a5u45qgu-pooler.us-east-2.aws.neon.tech:5432/neondb?sslmode=require
      - key: N8N_ENCRYPTION_KEY
        value: C8wIIRYGEM
    port: 5678
