services:
  - type: web
    name: n8n
    runtime: docker
    env: docker
    plan: free
    region: oregon # Choose your preferred region
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: your-username
      - key: N8N_BASIC_AUTH_PASSWORD
        value: your-password